<?php
/**
 * @file
 */

define('UOM_SPARQL_ENDPOINT', 'http://128.250.202.125:7001/joseki/oracle');
define('FAE_BASE', 'http://www.findanexpert.unimelb.edu.au/');

// Load the predefined SparQL queries.
module_load_include('inc', 'uom_fae_api', 'include/uom_fae_api.queries');

/**
 * Implements hook_flush_caches().
 */
function uom_fae_api_flush_caches() {
  return array('cache_uom_fae_api');
}

/**
 * Implements hook_admin_menu_cache_info().
 */
function uom_fae_api_admin_menu_cache_info() {
	// http://api.drupalize.me/api/drupal/function/hook_admin_menu_cache_info/7
	// Return an associative array whose keys denote internal identifiers for a particular caches (which can be freely defined, but should be in a module's namespace) and whose values are associative arrays containing
  $caches['uom_fae_api_update'] = array(
    'title' => t('Find an Expert queries'),
    'callback' => '_uom_fae_api_cache_clear',
  );
  return $caches;
}

/**
 * Callback to clear the uom_fae_api cache.
 */
function _uom_fae_api_cache_clear($cid = NULL, $wildcard = FALSE) {
  if (empty($cid)) {
    db_delete('cache_cache_uom_fae_api')->execute();
  }
  else {
    $query = db_delete('cache_uom_fae_api');
    if ($wildcard) {
      $query->condition('cid', $cid . '%', 'LIKE');
    }
    else {
      $query->condition('cid', $cid);
    }
    $query->execute();
  }
}

/**
 * Implements hook_menu().
 */
function uom_fae_api_menu() {
  $items['admin/config/services/uom-fae'] = array(
    'title' => t('Find an Expert'),
    'description' => t('Configure the Find an Expert API.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uom_fae_api_admin_form'),
    'access arguments' => array('administer uom fae api'),
    'file' => 'uom_fae_api.admin.inc',
  );
  $items['admin/config/services/uom-fae/api'] = array(
    'title' => t('Find an Expert API'),
    'description' => t('Configure the Find an Expert API.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uom_fae_api_admin_form'),
    'access arguments' => array('administer uom fae api'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'uom_fae_api.admin.inc',
    'weight' => -10,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function uom_fae_api_permission() {
  return array(
    'administer uom fae api' => array(
      'title' => t('Administer Find an Expert'),
      'description' => t('Configure the Find an Expert API.')
    ),
  );
}

/**
 * Return overview information for a person.
 */
function uom_fae_api_person_overview($uri, $args = array()) {
  // Mash in default arguments.
  $defaults = array(
    ':uri' => $uri,
  );
  $args += $defaults;

  $result = uom_fae_api_query(UOM_FAE_PERSON_OVERVIEW, $args);

  return (!empty($result['rows'])) ? $result['rows'][0] : t('Empty');
}

/**
 * Return a person's affiliation.
 */
function uom_fae_api_person_affiliation($uri, $args = array()) {
  $defaults = array(
    ':uri' => $uri,
  );
  $args += $defaults;

  $result = uom_fae_api_query(UOM_FAE_PERSON_AFFILIATION, $args);

  return (!empty($result['rows'])) ? $result['rows'] : NULL;
}

/**
 * Return a person's publications.
 */
function uom_fae_api_person_publications($uri, $args = array()) {
  // Mash in default arguments.
  $defaults = array(
    ':uri' => $uri,
  );
  $args += $defaults;

  $result = uom_fae_api_query(UOM_FAE_PERSON_PUBLICATIONS, $args);

  return (!empty($result['rows'])) ? $result['rows'] : NULL;
}

/**
 * Return a person's research.
 */
function uom_fae_api_person_research($uri, $args = array()) {
  // Mash in default arguments.
  $defaults = array(
    ':uri' => $uri,
  );
  $args += $defaults;

  $result = uom_fae_api_query(UOM_FAE_PERSON_RESEARCH, $args);

  return (!empty($result['rows'])) ? $result['rows'] : NULL;
}

/**
 * Return a person's awards.
 */
function uom_fae_api_person_awards($uri, $args = array()) {
  // Mash in default arguments.
  $defaults = array(
    ':uri' => $uri,
  );
  $args += $defaults;

  $result = uom_fae_api_query(UOM_FAE_PERSON_AWARDS, $args);

  return (!empty($result['rows'])) ? $result['rows'] : NULL;
}

/**
 * Return a person's linkages.
 */
/*
function uom_fae_api_person_linkages($uri, $args = array()) {
  // Mash in default arguments.
  $defaults = array(
    ':uri' => $uri,
  );
  $args += $defaults;

  $result = uom_fae_api_query(UOM_FAE_PERSON_LINKAGES, $args);

  return (!empty($result['rows'])) ? $result['rows'] : NULL;
}
*/

/**
 * Return a person's linkages, but without org label, only org uri
 */
function uom_fae_api_person_linkages_no_org_label($uri, $args = array()) {
  // Mash in default arguments.
  $defaults = array(
    ':uri' => $uri,
  );
  $args += $defaults;

  $result = uom_fae_api_query(UOM_FAE_PERSON_LINKAGES_NO_ORG_LABEL, $args);

  return (!empty($result['rows'])) ? $result['rows'] : NULL;
}

/**
 * Return org label 
 */
function uom_fae_api_person_linkages_org_label($uri, $args = array()) {
  // Mash in default arguments.
  $defaults = array(
    ':uri' => $uri,
  );
  $args += $defaults;

  $result = uom_fae_api_query(UOM_FAE_PERSON_LINKAGES_ORG_LABEL, $args);

  return (!empty($result['rows'])) ? $result['rows'] : NULL;
}



/**
 * Return a person's supervision.
 */
function uom_fae_api_person_supervision($uri, $args = array()) {
  // Mash in default arguments.
  $defaults = array(
    ':uri' => $uri,
  );
  $args += $defaults;

  $result = uom_fae_api_query(UOM_FAE_PERSON_SUPERVISION, $args);

  return (!empty($result['rows'])) ? $result['rows'][0] : NULL;
}

/**
 * Return contact information for a block on a person's profile.
 */
function uom_fae_api_person_contact($uri, $args = array()) {
  // Mash in default arguments.
  $defaults = array(
    ':uri' => $uri,
  );
  $args += $defaults;

  $result = uom_fae_api_query(UOM_FAE_PERSON_CONTACT, $args);

  return (!empty($result['rows'])) ? $result['rows'][0] : NULL;
}

/**
 * Return qualification information for a block on a person's profile.
 */
function uom_fae_api_person_qualifications($uri, $args = array()) {
  // Mash in default arguments.
  $defaults = array(
    ':uri' => $uri,
  );
  $args += $defaults;

  $result = uom_fae_api_query(UOM_FAE_PERSON_QUALIFICATIONS, $args);

  return (!empty($result['rows'])) ? $result['rows'] : NULL;
}

/**
 * Return research grants for a given organisation.
 */
function uom_fae_api_organisation_research($uri, $args = array()) {
  // Mash in default arguments.
  $defaults = array(
    ':uri' => $uri,
  );
  $args += $defaults;

  $result = uom_fae_api_query(UOM_FAE_ORGANISATION_GRANTS, $args);

  return (!empty($result['rows'])) ? $result['rows'] : NULL;
}


/**
 * Implements hook_uom_fae_api_query_alter().
 *
 * Add the XMLNS prefixes to the query and do the default
 * placeholder replacements.
 */
function uom_fae_api_uom_fae_api_query_alter(&$query, &$args) {
  $query = FAE_QUERY_PREFIX . $query;

  $defaults = array(
    ':timeout' => variable_get('uom_fae_api_timeout', 30),
    ':qid' => variable_get('uom_fae_api_qid', 'uom-fae-api'),
  );
  $args += $defaults;
}

/**
 * Helper that performs the SparQL query.
 *
 * Performs a vararg replace much like db_query() would. Merges in :uri if missing.
 *
 * Will query the raw response on success if caching is enabled.
 */
function uom_fae_api_query($query, $args = array()) {
  $period = variable_get('uom_fae_api_cache', 0);

  $endpoint = new stdClass();
  $endpoint->uri = variable_get('uom_fae_api_endpoint', UOM_SPARQL_ENDPOINT);

  // Modify the query and query argument.
  //
  // @see uom_fae_api_uom_fae_api_query_alter()
  drupal_alter('uom_fae_api_query', $query, $args);

  // Replace vars.
  $query = trim(strtr($query, $args));

  // Now that we have a full query, check if there is a cached result for it
  // and load that. Then continue, so that the alter hooks are called.
  $hash = md5($query);

  $cache = new stdClass();
  if ($period) {
    $cache = cache_get('uom_fae_api:' . $hash, 'cache_uom_fae_api');
  }

  // Check for cached results.
  if ($period && !empty($cache->data)) {
    $result = $cache->data;
  }
  else {
    $result = sparql_request($query, $endpoint);

    if ($result['result'] === FALSE) {
      // If an error occurs, log it.
      drupal_set_message(t('FaE SparQL query error'), 'error');
      watchdog('uom_fae_api', $query, WATCHDOG_ERROR);

      // If we have cached results, use them instead.
      if (!empty($cache->data)) {
        $result = $cache->data;
      }
    }
    elseif (empty($result['result']) && !empty($cache->data)) {
      // Use cached results if we have them.
      $result = $cache->data;
    }
    elseif ($period) {
      // Caching is enabled, throw the result into the cache!
      cache_set('uom_fae_api:' . $hash, $result, 'cache_uom_fae_api', time() + $period);
    }
  }

  // Allow the result to be rewritten.
  drupal_alter('uom_fae_api_query_result', $result);

  // Return the result.
  return $result['result'];
}

/**
 * Return a list of all callbacks defined via hook_uom_fae_api_callbacks().
 */
function uom_fae_api_callbacks() {
  $callbacks = &drupal_static(__FUNCTION__);

  if (!empty($callbacks)) {
    return $callbacks;
  }

  $module_info = system_get_info('module');

  // Get list of callbacks.
  foreach (module_implements('uom_fae_api_callbacks') as $module) {
    $functions = module_invoke($module, 'uom_fae_api_callbacks');
    foreach ($functions as $function => $name) {
      $callbacks[$module_info[$module]['name']][$function] = check_plain($name);
    }
  }

  ksort($callbacks);
  return $callbacks;
}

/**
 * Helper for quick access to publication types.
 */
function uom_fae_api_publication_types($key = NULL) {
  $types = array(
		'A'		=> t('Books'),
    'A1'  => t('Authored Research Books'),
    'A2'  => t('Edited Books'),
    'A3'  => t('Revised Books'),
    'A4'  => t('Translated Book'),
    'A5'  => t('Textbooks'),
    'A6'  => t('Authored Books Other'),

		'B'		=> t('Book Chapters'),
    'B1'  => t('Research Book Chapters'),
    'B2'  => t('Book Chapters Other'),

		'C'		=> t('Journal Articles'),
    'C1'  => t('Journal Articles Refereed'),
    'C2'  => t('Journal Articles Unrefereed'),
    'C3'  => t('Journal Articles Unrefereed Letters or Notes'),
    'C5'  => t('Other Refereed Contribution to Refereed Journals'),

		'D'		=> t('Major Reference works'),
    'D4'  => t('Major Reference works'),

		'E'		=> t('Editorship of Journal'),
    'E1'  => t('Editor (incl. Chief, Assoc. and other Editorial Roles)'),
    'E2'  => t('Editorial Board Member'),
    'E3'  => t('Guest Editor'),

		'F'		=> t('Conference Proceedings'),
    'F1'  => t('Fully Written Paper Refereed'),
    'F2'  => t('Fully Written Paper unrefereed'),

		'G'		=> t('Reports and Working Papers'),
    'G4'  => t('Major Reports and Working Papers'),
    'G5'  => t('Minor Reports and Working Papers'),
	
		'I'		=> t('Patents'),
		'I1'  => t('Patents'),

		'J11' => t('Major Published Works'),
    'J12' => t('Major Recorded Works'),
    'J13' => t('Major Exhibited Works'),
    'J6'  => t('Minor Published Works'),
    'J7'  => t('Minor Recorded Works'),
    'J8'  => t('Minor Exhibited Works'),
		'Ji'  => t('Creative Published Works'),
		'Jii' => t('Creative Recorded Works'),
		'Jiii'=> t('Creative Exhibited Works'),

		'K'		=> t('Curatorship'),
		'K1'	=> t('Curatorship of Web Based Exhibition'),
		'K2'	=> t('Curatorship of Exhibition/Event'),
		'K3'	=> t('Curatorship of Festival'),
		'K4'	=> t('Curatorship - Other'),

		'M'		=> t('Computer Software Products'),
    'M5'  => t('Computer software Products'),

		'N'		=> t('Audio-visual Recordings'),
    'N4'  => t('Audio-visual Recordings'),
		
		'P'		=> t('Performance'),
    'P1'  => t('Major Performance'),
    'P2'  => t('Minor Performance'),

		'R'		=> t('Research Higher Degree Theses'),
    'R11' => t('RHD Theses Passed'),
    'R12' => t('RHD Theses in Progress'),
		
		'U'		=> t('Performance of Unpublished Composition'),
		'U1'	=> t('1st Performance of Major Unpublished Composition'),
		'U2'  => t('1st Performance of Minor Unpublished Composition'),
  );

  return (empty($key)) ? $types : $types[$key];
}
